export const FB_ATTEMPTING = 'FB_ATTEMPTING';
export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS';
export const FB_LOGIN_FAILED = 'FB_LOGIN_FAILED';
export const REFRESH_PROFILE = 'REFRESH_PROFILE';

export const ORGANIZE_ATTEMPTING = 'ORGANIZE_ATTEMPTING';
export const ORGANIZE_FAILD = 'ORGANIZE_FAILD';
export const ORGANIZE_SUCCESS = 'ORGANIZE_SUCCESS';

export const MEETING_FETCHED = 'MEETING_FETCHED';

export const SINGLE_FETCHING = 'SINGLE_FETCHING';
export const SINGLE_DONE = 'SINGLE_DONE';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';